\c sportana;

DROP TABLE IF EXISTS Friends CASCADE;
DROP TABLE IF EXISTS Searchprofile CASCADE;
DROP TABLE IF EXISTS Times CASCADE;
DROP TABLE IF EXISTS Queue CASCADE;
DROP TABLE IF EXISTS GameWallPost CASCADE;
DROP TABLE IF EXISTS Notifications CASCADE;
DROP TABLE IF EXISTS Participant CASCADE;
DROP TABLE IF EXISTS FavoriteSports CASCADE;
DROP TABLE IF EXISTS Ratings CASCADE;
DROP TABLE IF EXISTS Game CASCADE;
DROP TABLE IF EXISTS Sport CASCADE;
DROP TABLE IF EXISTS Users CASCADE;