\c sportana;

DROP TABLE IF EXISTS Friends;
DROP TABLE IF EXISTS Times;
DROP TABLE IF EXISTS Queue;
DROP TABLE IF EXISTS GameWallPost;
DROP TABLE IF EXISTS Notifications;
DROP TABLE IF EXISTS Participant;
DROP TABLE IF EXISTS FavoriteSports;
DROP TABLE IF EXISTS Ratings;
DROP TABLE IF EXISTS Game;
DROP TABLE IF EXISTS Sport;
DROP TABLE IF EXISTS Users;